#ifndef __CONFIG_H_
#define __CONFIG_H_

#define FIFO_BUFFER_SIZE 500

#define EMPTY_BUFFER_WAIT_DELAY 100

#define DEFAULT_RESPONSE_DELAY 200

#define AP_CONNECTION_DELAY 5000

#define HTTP_TIMEOUT 5000

#define RESPONSE_LINE_BUFFER_LENGTH 100

#define DOWNLOAD_CHUNK_SIZE 200

enum EEPROM_VARS {
    App1Size = 0x00000001UL,
    App1Version,
    App2Size,
    App2Version
};

#endif