#ifndef __CONFIG_H_
#define __CONFIG_H_

#define EMPTY_BUFFER_WAIT_DELAY 100

#define EMPTY_BUFFER_RETRY_COUNT 5

#define DEFAULT_RESPONSE_DELAY 200

#define AP_CONNECTION_DELAY 5000

#define HTTP_TIMEOUT 5000

#define RESPONSE_LINE_BUFFER_LENGTH 100

#endif